module.exports = {
	"bangladesht3": "bangladesh",
    "belgiumt3": "belgium",
    "chinat3": "china",
    "columbia": "colombia",
    "costarica": "costa rica",
    "denmarkt3": "denmark",
    "finlandt3": "finland",
    "francet3": "france",
    "germanyt3": "germany",
    "greecet3": "greece",
    "indonesiat3": "indonesia",
    "italyt3": "italy",
    "namibiat3": "namibia",
    "netherlandst3": "netherlands",
    "pakistant3": "pakistan",
    "perut2": "peru",
    "philippinescompletet3": "philippines",
    "philippinest3": "philippines",
    "phillipinest3": "philippines",
    "saudiarabia": "saudi arabia",
    "spaint3": "spain",
    "srilanka": "sri lanka",
    "srilankat3": "sri lanka",
    "uae": "united arab emirates",
    "ukt3": "united kingdom",
    "united kingdom": "united kingdom",
    "usa": "united states",
    "united states": "united states",
    "vietnamt3": "vietnam",
    "us": "united states",
    "uk": "united kingdom",
    "united-states-of-america": "united states",
    "unitedkingdom": "united kingdom",
    "uk t3": "united kingdom",
    "brazil t3": "brazil",
    "bangladesh t3": "bangladesh",
    "denmark t3": "denmark",
    "costa rica t1": "costa rica",
    "fiji t3": "fiji",
    "panama t1": "panama",
    "usa t1": "united states",
    "china t3": "china",
    "columbia t1": "columbia",
    "phillipines t3": "phillipines",
    "pakistan t3": "pakistan",
    "pakistan t1": "pakistan",
    "uruguay t1": "uruguay",
    "spain t3": "spain",
    "ghana t3": "ghana",
    "namibia t3": "namibia",
    "malawi t3": "malawi",
    "rwanda t3": "rwanda",
    "zimbabwe t3": "zimbabwe",
    "germany t3": "germany",
    "moldova t3": "moldova",
    "indonesia t3": "indonesia",
    "uzbekistan t3": "uzbekistan",
    "burundi t3": "burundi",
    "congo t3": "congo",
    "central africa t3": "central africa",
    "vietnam t3": "vietnam",
    "turkey t3": "turkey",
    "sri lanka t3": "sri lanka",
    "belgium t3": "belgium",
    "tanzania t3": "tanzania",
    "philippines complete t3": "philippines complete",
    "netherlands t3": "netherlands",
    "cameroon t3": "cameroon",
    "uk t1": "united kingdom",
    "brazil t1": "brazil",
    "bangladesh t1": "bangladesh",
    "denmark t1": "denmark",
    "fiji t1": "fiji",
    "china t1": "china",
    "phillipines t1": "phillipines",
    "spain t1": "spain",
    "ghana t1": "ghana",
    "namibia t1": "namibia",
    "malawi t1": "malawi",
    "rwanda t1": "rwanda",
    "zimbabwe t1": "zimbabwe",
    "germany t1": "germany",
    "moldova t1": "moldova",
    "indonesia t1": "indonesia",
    "uzbekistan t1": "uzbekistan",
    "burundi t1": "burundi",
    "congo t1": "congo",
    "central africa t1": "central africa",
    "vietnam t1": "vietnam",
    "turkey t1": "turkey",
    "sri lanka t1": "sri lanka",
    "belgium t1": "belgium",
    "tanzania t1": "tanzania",
    "philippines complete t1": "philippines complete",
    "philippines t1": "philippines",
    "netherlands t1": "netherlands",
    "cameroon t1": "cameroon",
    "bolivia t1": "bolivia",
    "mexico t1": "mexico",
    "ecuador t1": "ecuador",
    "paraguay t1": "paraguay",
    "argentina t1": "argentina",
    "ethiopia t1": "ethiopia",
    "chile t1": "chile",
    "venezuela t1": "venezuela",
    "peru t1": "peru",
    "peru t2": "peru"
}
