module.exports = {
    "bangladesht3": "bangladesh",
    "belgiumt3": "belgium",
    "chinat3": "china",
    "columbia": "colombia",
    "costarica": "costa rica",
    "czech-republic": "czech republic",
    "denmarkt3": "denmark",
    "finlandt3": "finland",
    "francet3": "france",
    "germanyt3": "germany",
    "greecet3": "greece",
    "indonesiat3": "indonesia",
    "italyt3": "italy",
    "namibiat3": "namibia",
    "netherlandst3": "netherlands",
    "pakistant3": "pakistan",
    "perut2": "peru",
    "philippinescompletet3": "philippines",
    "philippinest3": "philippines",
    "phillipinest3": "philippines",
    "saudiarabia": "saudi arabia",
    "spaint3": "spain",
    "srilanka": "sri lanka",
    "srilankat3": "sri lanka",
    "uae": "united arab emirates",
    "ukt3": "united kingdom",
    "united-kingdom": "united kingdom",
    "usa": "united states",
    "viet-nam": "vietnam",
    "vietnamt3": "vietnam",
    "vn-viet-nam": "vietnam",
    "us": "united states",
    "uk": "united kingdom",
    "united-states-of-america": "united states",
    "korea-republic-of": "south korea",
    "republic-of-korea": "south korea",
    "new-zealand": "new zealand",
    "china-taiwan": "taiwan",
    "shipment-data-egypt": "egypt",
    "shipment-data-global-exporters-importers-export": "",
    "af-afghanistan": "afghanistan",
    "al-albania": "albania",
    "dz-algeria": "algeria",
    "ad-andorra": "andorra",
    "ao-angola": "angola",
    "ag-antigua-and-barbuda": "antigua-and-barbuda",
    "ar-argentina": "argentina",
    "am-armenia": "armenia",
    "au-australia": "australia",
    "at-austria": "austria",
    "az-azerbaijan": "azerbaijan",
    "bs-bahamas": "bahamas",
    "bh-bahrain": "bahrain",
    "bd-bangladesh": "bangladesh",
    "bb-barbados": "barbados",
    "by-belarus": "belarus",
    "be-belgium": "belgium",
    "bz-belize": "belize",
    "bj-benin": "benin",
    "bt-bhutan": "bhutan",
    "bo-bolivia": "bolivia",
    "ba-bosnia-and-herzegovina": "bosnia-and-herzegovina",
    "bw-botswana": "botswana",
    "br-brazil": "brazil",
    "bn-brunei": "brunei",
    "bg-bulgaria": "bulgaria",
    "bi-burundi": "burundi",
    "kh-cambodia": "cambodia",
    "cm-cameroon": "cameroon",
    "ca-canada": "canada",
    "cl-chile": "chile",
    "cn-china": "china",
    "co-colombia": "colombia",
    "km-comoros": "comoros",
    "cr-costa-rica": "costa-rica",
    "hr-croatia": "croatia",
    "cu-cuba": "cuba",
    "cy-cyprus": "cyprus",
    "dk-denmark": "denmark",
    "dj-djibouti": "djibouti",
    "dm-dominica": "dominica",
    "ec-ecuador": "ecuador",
    "eg-egypt": "egypt",
    "ee-estonia": "estonia",
    "et-ethiopia": "ethiopia",
    "fj-fiji": "fiji",
    "fi-finland": "finland",
    "fr-france": "france",
    "ga-gabon": "gabon",
    "gm-gambia": "gambia",
    "ge-georgia": "georgia",
    "de-germany": "germany",
    "gh-ghana": "ghana",
    "gr-greece": "greece",
    "gd-grenada": "grenada",
    "gt-guatemala": "guatemala",
    "gn-guinea": "guinea",
    "gy-guyana": "guyana",
    "ht-haiti": "haiti",
    "hu-hungary": "hungary",
    "is-iceland": "iceland",
    "in-india": "india",
    "id-indonesia": "indonesia",
    "ir-iran": "iran",
    "iq-iraq": "iraq",
    "ie-ireland": "ireland",
    "il-israel": "israel",
    "it-italy": "italy",
    "jm-jamaica": "jamaica",
    "jp-japan": "japan",
    "jo-jordan": "jordan",
    "kz-kazakhstan": "kazakhstan",
    "ke-kenya": "kenya",
    "ki-kiribati": "kiribati",
    "kw-kuwait": "kuwait",
    "kg-kyrgyzstan": "kyrgyzstan",
    "la-laos": "laos",
    "lv-latvia": "latvia",
    "lb-lebanon": "lebanon",
    "ls-lesotho": "lesotho",
    "lr-liberia": "liberia",
    "ly-libya": "libya",
    "lu-luxembourg": "luxembourg",
    "mg-madagascar": "madagascar",
    "mw-malawi": "malawi",
    "my-malaysia": "malaysia",
    "mv-maldives": "maldives",
    "mt-malta": "malta",
    "mh-marshall-islands": "marshall islands",
    "mr-mauritania": "mauritania",
    "mu-mauritius": "mauritius",
    "mx-mexico": "mexico",
    "fm-micronesia": "micronesia",
    "md-moldova": "moldova",
    "mc-monaco": "monaco",
    "mn-mongolia": "mongolia",
    "me-montenegro": "montenegro",
    "ma-morocco": "morocco",
    "mz-mozambique": "mozambique",
    "mm-myanmar": "myanmar",
    "na-namibia": "namibia",
    "nr-nauru": "nauru",
    "np-nepal": "nepal",
    "nl-netherlands": "netherlands",
    "nz-new-zealand": "new zealand",
    "ni-nicaragua": "nicaragua",
    "ne-niger": "niger",
    "ng-nigeria": "nigeria",
    "kp-north-korea": "north korea",
    "no-norway": "norway",
    "om-oman": "oman",
    "pk-pakistan": "pakistan",
    "pw-palau": "palau",
    "pa-panama": "panama",
    "pg-papua-new-guinea": "papua new guinea",
    "py-paraguay": "paraguay",
    "pe-peru": "peru",
    "ph-philippines": "philippines",
    "pl-poland": "poland",
    "pt-portugal": "portugal",
    "qa-qatar": "qatar",
    "ro-romania": "romania",
    "ru-russia": "russia",
    "rw-rwanda": "rwanda",
    "kn-saint-kitts-and-nevis": "saint kitts and nevis",
    "lc-saint-lucia": "saint lucia",
    "vc-saint-vincent-and-the-grenadines": "saint vincent and the grenadines",
    "ws-samoa": "samoa",
    "sm-san-marino": "san marino",
    "st-sao-tome-and-principe": "sao tome and principe",
    "sa-saudi-arabia": "saudi arabia",
    "sn-senegal": "senegal",
    "rs-serbia": "serbia",
    "sl-sierra-leone": "sierra leone",
    "sg-singapore": "singapore",
    "sk-slovakia": "slovakia",
    "si-slovenia": "slovenia",
    "sb-solomon-islands": "solomon islands",
    "so-somalia": "somalia",
    "za-south-africa": "south africa",
    "kr-south-korea": "south korea",
    "es-spain": "spain",
    "lk-sri-lanka": "sri lanka",
    "sd-sudan": "sudan",
    "sr-suriname": "suriname",
    "se-sweden": "sweden",
    "ch-switzerland": "switzerland",
    "sy-syria": "syria",
    "tw-taiwan": "taiwan",
    "tj-tajikistan": "tajikistan",
    "tz-tanzania": "tanzania",
    "th-thailand": "thailand",
    "tg-togo": "togo",
    "to-tonga": "tonga",
    "tn-tunisia": "tunisia",
    "tr-turkey": "turkey",
    "tv-tuvalu": "tuvalu",
    "ug-uganda": "uganda",
    "ua-ukraine": "ukraine",
    "ae-united-arab-emirates": "united arab emirates",
    "gb-united-kingdom": "united kingdom",
    "us-united-states": "united states",
    "uy-uruguay": "uruguay",
    "uz-uzbekistan": "uzbekistan",
    "vu-vanuatu": "vanuatu",
    "ve-venezuela": "venezuela",
    "vn-vietnam": "vietnam",
    "ye-yemen": "yemen",
    "zm-zambia": "zambia",
    "zw-zimbabwe": "zimbabwe",
    "ialy": "italy",
    "united-statesamerica": "united states",
    "kr-republic-of-korea": "south korea",
    "hk-hong-kong": "hong kong",
    "kp-korea-democratic-peoples-republic-of": "north korea",
    "democratic-peoples-republickorea": "north korea",
    "yu-yugoslavia": "yugoslavia",
    "co-columbia": "colombia",
    "cv-cape-verde": "cape-verde"
}